### ISSUE TITLE
[BugRequest] A11YJ Slackチームのリンク誘導が残っている

### ISSUE THREAD

**Issue by yamanoku** [a11yj/accrefs#128]
# バグレポート

## バグを提案する対象

A11YJ Slackは現在廃止されたが、リンク誘導がまだ残っている

https://github.com/a11yj/accrefs/blob/deccbb317131ca9739f3aff4fb065b33b52b6ceb/src/templates/home.pug#L37-L39

## バグの詳細

ホーム下部の「ウェブサイトに貢献」箇所

## バグの解決案

ウェブアクセシビリティDiscordチャンネルへのリンク誘導とその後の流れを明記したほうがよさそう

**Comment by oti** [comment]
@yamanoku ありがとうございます。連休中に対応できると思います。

**Comment by oti** [comment]
ウェブアクセシビリティDiscordは管理者が異なるので、一旦リンクをトルツメして対応しました。
