### ISSUE TITLE
スタイルを整える

### ISSUE THREAD

**Issue by oti** [a11yj/accrefs#2]
現状はワイヤーをそのままHTMLに落としたようなビジュアルなので、これを整えたいです。

画面要件的な意味合いで要素が置かれている状態なので、ビジュアルについては今のレイアウトを踏襲しなくても構いません。

Patches Welcome!

**Comment by yuheiy** [comment]
とりあえず https://yuheiy.github.io/hogerefsproto/

**Comment by oti** [comment]
#38 と #39 で対応される予定です。#39 のマージ後、こちらもcloseします。
