### ISSUE TITLE
「ピンク本」という表記の検討

### ISSUE THREAD

**Issue by 38mot** [a11yj/accrefs#33]
なぜ検討が必要か
- 「ピンク本」を知らない人がこのサイトへ訪れた場合、現状1階層下の「ピンク色の本こと、『デザイニングWebアクセシビリティ』が定番です。」の項目まで辿り着けないと「ピンク本が何なのか」分からない
- 「ピンク本」という表記をこのサイトで使用することで、アクセシビリティ界隈ではこれが当たり前の呼び方と思われてしまうことへの不安

どうするか
- 「ピンク本」から「デザイニングWebアクセシビリティ」に表記を変更する
- 冒頭に、「このサイトで言うピンク本とは、デザイニングWebアクセシビリティという書籍のことを指します。」など記述する

個人的には「デザイニングWebアクセシビリティ」に表記統一で良いのでは、と思っています。

**Comment by oti** [comment]
accrefsはさまざまな人に使ってもらえるよう、隠語的な記述を用いないようにするのは賛成です。

**Comment by bakera** [comment]
サイトにせよ書籍にせよ、基本的に固有名詞は全て略さずに正式名称で表記すべきだと思います

**Comment by oti** [comment]
その通りですね！

今回（v1）はウェブサイト版に移植する目的が強いので、すぐにわかる範囲でしか原稿修正を行わないと思われますが、定期的にメンテしてサイト内の文言を直していく必要はありそうです。

本イシューについては #36 で解決済みとし、ひとまず close します。

他のリンクで正式名称ではないもの（一般の認知からかけ離れた隠語）を使っている箇所がありましたら、お気軽にイシューなりでご連絡いただければと思います。

@38mot @bakera ありがとうございました！
