### ISSUE TITLE
READMEの体裁を整える

### ISSUE THREAD

**Issue by oti** [a11yj/accrefs#34]
related #5 

alpha版から公開版v1 にするにあたって、多くの人からコントリビュートを受け付けられる体制にする必要があると考えます。

現状READMEは、開発者向けの手順書になっているので、大枠で下記のような形に改修します。文面の詳細は詰められていないので、増減しますし、アイデアがあればコメントください。

```
# accrefs -Webアクセシビリティ関連のまとめ- 

accrefs.jp はWebアクセシビリティに関する情報をまとめたリンク集です。

## まとめている情報の要件

Webアクセシビリティに関する内容であることを大前提として、

- 参照できるパーマリンクがあること
- 出来るだけ新しい情報であること
- 技術的なこと
- 結果報告的なこと
- 組織やチームの取り組み的なこと
- 当事者のこと
- 

## リンクを追加・修正する

accrefsはリンク掲載について、誰からの提案でも受け付けています。提案はオンライン場では下記のいずれかでリクエストを送ることができます。

- Googleフォームでリクエストする
- リポジトリにイシューを立てる
- A11YJ Slackチームに参加し、発言する

リンクだけでなく、リンクに添えられた本文の修正も上記のいずれから遠慮なくリクエストしてください！

## リンク以外のリクエスト

掲載されているリンクやその本文以外についての要望も受け付けています。

フォントサイズやコントラスト、マークアップやスタイルシートに問題がある場合は、リポジトリのイシューで報告してください。

## より高度なリクエスト

accrefs はGitHubの本リポジトリで開発しており、Forkしてプルリクエストを送ることができます。

ウェブサイトについてより高度なリクエストがある場合は、プルリクエストを送ってください。

ローカルでの開発手順は INSTALLMENT.md に記載しています。

## ライセンス

特にないけど書かないといけない気もするので、「特にない」というライセンスを書くか？

## 謝辞

accrefs はA11YJ Slackメンバーと有志の協力によって制作されました。この場を借りて深くお礼を申し上げます。
```

**Comment by jidaikobo-shibata** [comment]
基本的にいい感じだと思いますがいくつかコメントを。

> 出来るだけ新しい情報であること

古くても、良い意味で枯れていて不変の情報であれば、拒否することはないと思います。
「なんでアクセシビリティに取り組むか」みたいな文書は古くてもいいものがあるでしょうし。
技術系でもaltバナシだったら、古くてもよいものは見たことがあります。

> A11YJ Slackチームに参加し、発言する

チャネル（#a11y_matome_site）まで明記しちゃうのがアリかナシか？

あと、そもそも参加のリンクがあってもいいかも。
https://a11yj.slack.com

> 特にないけど書かないといけない気もするので、「特にない」というライセンスを書くか？

「利用資格、利用料金はありません。転載等は制限しません。勉強会などで使うときには、ネタもとにしたと言ってくれれば嬉しいですが、言わなくても構いません」みたいな？

もしかしたら、おきまりのdisclaimerはあったほうがいいかも。興ざめかなぁ。
「リンク先の情報を鵜呑みにして、損害が発生しても責任を負いません」

**Comment by oti** [comment]
> 古くても、良い意味で枯れて〜

これはもちろんアグリーです。よくよく考えたら、元のドキュメントに追加ポリシーがあったので、これをリファインするのが良いかなと思いました。

https://docs.google.com/document/d/1EiMwdl7J6d7tE5imTZ670PkdTp-rejxaOqiAgjE9TDU/edit#heading=h.h9y1d1k0axp3

> チャネル（#a11y_matome_site）まで明記しちゃうのがアリかナシか？

リンクは、自己 invite 送れる Heroku のリンクを追記するつもりでした。チャンネル明記もアリだと思います。そもそも公開チャンネルなので、チームに参加したら誰でも閲覧できますからね。

> 「利用資格、利用料金は〜

良さそうです。料金的な話はヌキで、もっとシンプルになっても良いかもですね。今思いついたのは「無断転載・無断引用大歓迎！　発見次第即乾杯！！」です。

> しかしたら、おきまりのdisclaimerは〜

ここは議論したいですね。

**Comment by magi1125** [comment]
>元のドキュメントに追加ポリシーがあったので、これをリファインするのが良い

賛成〜

>今思いついたのは「無断転載・無断引用大歓迎！　発見次第即乾杯！！」です。

最高。

>ここは議論したいですね

以下のような感じではどうだろう。

---
紹介しているサイトにおいては、他のサイトと主張が異なっていたり、特定の状況のみで成立するようなTipsであったりするケースもあります。何を参考にするか、何を取り入れるかは適宜自身の判断でご利用ください。

**Comment by bakera** [comment]
表現の問題だと思いますが、「ライセンスが特にない」というのは「自由に利用して良い」ということではなく、「利用をまったく許諾していない」という意味になります。もしくは「多分利用が許されるが書かれていないので不明」と解釈されるかもしれませんが、いずれにしても利用困難になります。
あまりこだわりがなく、普通に自由に利用してほしいのであれば、深く考えずに CC-BY くらいにしておけば良いのではないでしょうか。

**Comment by oti** [comment]
> 紹介しているサイトにおいては、他のサイトと主張が異なっていたり、特定の状況のみで成立するようなTipsであったりするケースもあります。何を参考にするか、何を取り入れるかは適宜自身の判断でご利用ください。

これはウェブサイト側にも記入が必要な「お断り」な気がしてきました。

**Comment by oti** [comment]
> （前略）深く考えずに CC-BY くらいにしておけば良いのではないでしょうか。

BY が気になるのですが、[CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.ja)だと

> あなたの従うべき条件は以下の通りです。
> 
> 表示 — あなたは 適切なクレジットを表示し、ライセンスへのリンクを提供し、変更があったらその旨を示さなければなりません。これらは合理的であればどのような方法で行っても構いませんが、許諾者があなたやあなたの利用行為を支持していると示唆するような方法は除きます。
> 
> 追加的な制約は課せません — あなたは、このライセンスが他の者に許諾することを法的に制限するようないかなる法的規定も技術的手段 も適用してはなりません。

とあります。誰かがaccrefsから引用する際、それがaccrefsに掲載されていたことを「表示する」要件すら不要ではないかと感じます。なので、[CC 0](https://creativecommons.org/publicdomain/zero/1.0/deed.ja)でどうでしょうか？　やりすぎ？？

CC BYでもCC 0でも、リンク先のコンテンツ自体の著作権はそれぞれで規定されているライセンスに従ってください的な注記はあったほうが良さそうですね。

**Comment by jidaikobo-shibata** [comment]
`CC 0` いーんじゃないでしょか。注記は常識だとしても、入れておく方がいいと思います。
ここいらへんしっかりしておいた方が、情報提供もしやすくなると思います。

**Comment by yamanoku** [comment]
```
## まとめている情報の要件
Webアクセシビリティに関する内容であることを大前提として、
- 技術的なこと
- 結果報告的なこと
- 組織やチームの取り組み的なこと
```

細かいですが「的なこと」を言い換えたい感じです。
厳密しすぎても良くないとは思ってますが

- 技術で解決できること
- 実施した結果の報告
- 組織・チームでの取り組みについて

みたいな感じ。

**Comment by momdo** [comment]
https://github.com/a11yj/accrefs/issues/34#issuecomment-525229717

- 技術に関すること
- 結果報告に関すること
- 組織やチームの取り組みに関すること

実はこうでは説（知らんけど）

**Comment by yamanoku** [comment]
良さそうです！
指摘しといて「技術的な〜」は巻き込みしてる気がしてきました…

**Comment by magi1125** [comment]
というか記載要件はこれベースが良さげかもという意見もあり、ご検討いただければと。
https://docs.google.com/document/d/1EiMwdl7J6d7tE5imTZ670PkdTp-rejxaOqiAgjE9TDU/edit#heading=h.h9y1d1k0axp3

**Comment by bakera** [comment]
個人的にはCC 0とすることは慎重に判断したいです。出典なしでまるごとコピペして営利利用されても文句が言えない状態になりますので……。
普通に利用する分には、CC BY でも問題になることはないと思います。

**Comment by jidaikobo-shibata** [comment]
なるほど……。ふだんからWTFPLみたいなライセンスで活動していることが多いので、個人的には

> 出典なしでまるごとコピペして営利利用されても文句が言えない状態

でも、いーや、という気分なんですが、みんながみんなそうではないでしょうね。

**Comment by oti** [comment]
@bakera accrefsに掲載されることが、出典にとって不利益にならないようにすることは大事ですね……CC 0のリスクについて認識が甘かったです。ありがとうございます。

CC BY で利用者の利便性と出典の安全性がバランスよく取れると考えを改めました。

ライセンスについて他に特に意見がなければ、accrefsはCC BYでいきたいと思います。

**Comment by momdo** [comment]
個人的にはライセンスはよしなにしてくれていいと思いますけど、BYの名義はどうするので？

**Comment by oti** [comment]
> BYの名義

「A11YJ Slack Team」とか……？　もんどさんは名義の案はありますか？

**Comment by jidaikobo-shibata** [comment]
> 「A11YJ Slack Team」とか……？　もんどさんは名義の案はありますか？

もんどさんじゃないけど、任意団体が著作権を主張するのはアリだと聞いた覚えがあるし、おかしくないんじゃないでしょうか。

**Comment by momdo** [comment]
>「A11YJ Slack Team」とか……？　もんどさんは名義の案はありますか？

それでよいのでは（特に私からの案はありません）

参考リソース
- https://developer.mozilla.org/ja/docs/MDN/About
- https://ja.wikipedia.org/wiki/Wikipedia:%E3%82%A6%E3%82%A3%E3%82%AD%E3%83%9A%E3%83%87%E3%82%A3%E3%82%A2%E3%82%92%E4%BA%8C%E6%AC%A1%E5%88%A9%E7%94%A8%E3%81%99%E3%82%8B
- https://wiki.suikawiki.org/n/WikiPageLicense

**Comment by magi1125** [comment]
>元のドキュメントに追加ポリシーがあったので、これをリファインするのが良い

これですが、どんな感じでリファインするといいかなーと考えてみます。もう少しかためで簡潔でコンパクトにする感じかしら。いったんそんな感じでやってみますが、なにかご意見あればください。
https://docs.google.com/document/d/1EiMwdl7J6d7tE5imTZ670PkdTp-rejxaOqiAgjE9TDU/edit#heading=h.h9y1d1k0axp3

**Comment by magi1125** [comment]
編集ルール、サマるとこんな感じになると思いました。

- ウェブサイトやアプリケーション、ソフトウェアのアクセシビリティに関係する資料を掲載してください
- タグおよび項目の追加・更新・削除は誰でも行えます。なお、タグや項目の削除を行う場合はその理由を示してください
- 掲載する際は、資料の概要やおすすめする理由を概要文として記載してください
- 日本語の資料を優先してください。海外の資料は、日本語で代替するものがなさそうな場合に掲載してください
- JIS X 8341-3:2010 が公表された、2010年以降の資料の掲載を推奨します。ただし、それ以前の資料でも有用だと考えられる場合は掲載してください
- 有用と考えられる資料が載っていない場合、単に見落としの可能性が高いと考えられます。積極的に掲載してください
- 自身が書いたブログや登壇資料の掲載も歓迎します。このサイトを使って自身の主張をより多くの人に届けてください
- 判断に迷うことがあれば、いつでも A11YJ Slack の #a11y_matome_site までご質問ください
- このルールに対する提案などあれば、いつでも A11YJ Slack の #a11y_matome_site までお寄せください

**Comment by oti** [comment]
長い！
このボリュームだと読まないと思います。もっと入り口が簡単な必要がありそうです。

**Comment by magi1125** [comment]
そうねえ、どのへんまで削れるかなー。以下あたりが気にしていることなんで、それを分ければいいかな。

- ウェブとかデジタルメディアと関係ないアクセシビリティネタが増えること
- タグとか項目を無言で消すこと
- 概要文を書かずに無言でタグや項目を足すこと
- 英語の資料ばかりが増殖すること
- 2010年以前のJISやWCAG2.0以前を前提とした資料が増えること
- 「これが載ってないのはなんか理由があるんだろう」と忖度して載せないこと
- 自分なんてまだまだだから、みたいな謙遜で自分の記事やスライドを載せないこと

**Comment by oti** [comment]
NGを示すのは良いですね。ちょっと数日寝かしてから、過剰な説明がないか見直したいです。

**Comment by momdo** [comment]
というか議論中であることを示すか、合意の取れたところをとっとと反映するかすべきなのでは。

**Comment by oti** [comment]
そうですね。プルリクにして、項目ごとにサブプルリクででやりますー

**Comment by oti** [comment]
このイシューはロックします。項目ごとの議論は #48 で示されているプルリクエスト上で行なってください。みなさま引き続きよろしくお願いいたします。
