### ISSUE TITLE
コントリビュートの体制を整える

### ISSUE THREAD

**Issue by oti** [a11yj/accrefs#5]
accrefsはどなたからの掲載リクエストも受け付ける姿勢です。このため、Git・GitHubでコミットできない人のために、他の窓口を用意する必要があります。

1. Googleフォーム導線
2. Slackチームへの導線

GitHub以外では、まず上記２つを準備したいです。

**Comment by yamanoku** [comment]
`2. Slackチームへの導線` っていつものherokuリンクだけになる感じですかね
ジョインした後、`#a11y_matome_site` にリンクを書いてもらうみたいな感じまで整えたほうが優しいのかな

**Comment by yamanoku** [comment]
Googleフォーム、試しに作ってみました
https://docs.google.com/forms/d/e/1FAIpQLSfNFQpTJJFhTyVHnaDjadMa6o7gJQhjs0-6LoHs6L5LJs5tkQ/viewform

編集リンク
https://docs.google.com/forms/d/1a1Elf1m0KHKco0sd56zX35DYVzjGD1lqhUc-Tq4xlNM/edit?usp=sharing

**Comment by oti** [comment]
@yamanoku ありがとうございます！

> 2. Slackチームへの導線 っていつものherokuリンクだけになる感じですかね
> ジョインした後、#a11y_matome_site にリンクを書いてもらうみたいな感じまで整えたほうが優しいのかな

#51 で[作業中](https://github.com/a11yj/accrefs/pull/51/files#diff-04c6e90faac2675aa89e2176d2eec7d8R22)で、

> - [A11YJ Slackチームにjoin](https://a11yj.herokuapp.com/)し、`#a11y_matome_site`チャンネルでリクエストする

という説明文を追加しようとしています。チャンネルにjoinした後のアクションを何か追記してみます。

Googleフォームもありがとうございます。手元で準備していたのはこちらで、

https://docs.google.com/forms/d/e/1FAIpQLSeDgNqLGZ2-CESSxW-uuJI240pNR5yS9mC3g1xE9IU5B2eA4w/viewform

タグが複数選択できるようにチェックボックスにしています。yamanokuさんのと比べつついい感じにマージしようと思いますー。

**Comment by yamanoku** [comment]
Slackチームへの導線、了解です！

> タグが複数選択できるようにチェックボックス

なるほど。たしかに複数の場合もありますね。
