### ISSUE TITLE
ビルドをいい感じにする

### ISSUE THREAD

**Issue by oti** [a11yj/accrefs#6]
現状はGitHub Pagesで `/docs` 配下をドキュメントルートとしているが、生成物をコミットするためチョット気持ちが悪い。

Circle CIなどを利用して、リポジトリはソースファイルの管理飲みに興味を持つように変更したい。

アイデア（PRs）募集です。

**Comment by oti** [comment]
Netrifyですかね。あんまり管理画面を増やしたくないなーという気持ち。GitHub内だけでできるならそうしたい。

**Comment by yuheiy** [comment]
Netlifyを使うと、ブランチをpushすると勝手にステージング作ってくれるようにできるので便利な瞬間がいつか来るかもしれないです。

**Comment by masuP9** [comment]
Netrify 良さそうだけど、管理画面増えるのもなーはわかる。

**Comment by yuheiy** [comment]
GitHub Actionsでワンチャンあるかもしれません
https://twitter.com/TartanLlama/status/1164148737125638144

**Comment by oti** [comment]
GitHub Actions狙ってるけどまだ来ないし、それまでは `/docs` でいいかなとか思ってはいる。

**Comment by masuP9** [comment]
僕のリポジトリだと来てるから準備だけしておこうかな

**Comment by masuP9** [comment]
準備だけした

**Comment by oti** [comment]
@yuheiy @masuP9 @magi1125 `/docs` をコミットするのが堪えられなかったので、GitHub Actionsが来るまではNetlifyにホストして自動ビルドを設定することにします。

GitHub側のホスティングを切ってNetlifyに向けるところまでやりました。

`/docs` を rm って .gitignore に登録するPRをこれから作ります。 -> 作りました #19

**Comment by oti** [comment]
プルリクのステージング作ってくれるのスーパーウルトラデラックスありがたすぎる。もうNetlifyのままの方がいいのでは？？

**Comment by masuP9** [comment]
Netlify のままで良さそう

**Comment by oti** [comment]
GitHub Actionsに乗り換えるメリットがなさそうなのでcloseします。
