### ISSUE TITLE
[AddRequest] 「アクセシビリティ関連イベントの一覧」のタグを新規に追加する

### ISSUE THREAD

**Issue by oti** [a11yj/accrefs#74]
# 追加リクエスト

参考資料の追加の前に、これにふさわしいタグがない気がするので提案です。

## 追加する参考資料のURL

https://paper.dropbox.com/doc/201969--Aqm6qRNp0oh0C90b2zL5dV2DAg-jIGbxLP0sbn8f2EL0dAkt

## 参考資料を登録するタグ

~「アクセシビリティ関連のイベント」~「アクセシビリティ関連イベントの一覧」のようなラベルでどうでしょうか？

## 参考資料の説明文

タグが出来てから別PRで考えたいです。

**Comment by magi1125** [comment]
@oti ええと思います。あー年の扱いどうしよ。

- ラベルに2019とか含める？（「2019年開催のアクセシビリティ関連イベント」的な）
- むしろ年だけのタグを別途作る？でも資料の初出年とかでつけたりつけなかったりして雑になりそう

**Comment by yamanoku** [comment]
年、タグとしては不要な気はします（年内のものは年内で理解できそうだけど、昔のものを追加するときは振り返ったり探さないといけない）

**Comment by oti** [comment]
あ、まとめをaccrefsに移植する意図はなくて、あくまで元のページを尊重したいんですよね。なのでやりたいことは「アクセシビリティ関連イベントの一覧」みたいなタグを作ることでした。

**Comment by magi1125** [comment]
あーそういうこと。
slackで

>年単位であったイベントまとめページもあったらいいのかなと思った

って話があったので。

**Comment by oti** [comment]
accrefsはメタブックマーク的なウェブサイトに徹したい気持ち。年単位でまとめるのは別のところでやって欲しいんですよね。まとまめられているコンテンツにリンクしたい。

年別については、accrefsには子カテゴリがないので「2019年の〜一覧」「2020年の〜一覧」というふうに増やしていく感じになると思うんですが、なんか違う気がします。

「アクセシビリティ関連イベントの一覧」のタグの中に、2019年の一覧へのリンクや2018年の一覧へのリンクがあったほうがそれっぽいというか。なんならまとめを作った人の裁量で「2019年のアクセシビリティ関連イベントでスライドが公開されている一覧」とか「動画アーカイブがある一覧」とかそういう尺度になっていても良くて、それらのまとめをaccrefsでまとめているという構造になっている方が俯瞰しやすいなって思うのです。

**Comment by magi1125** [comment]
@oti 完全に理解した。ナイスIA。それがいいと思いました。
accrefs内の個々のコンテンツにイベントタグとか年タグが付くのかなーと思ったけど、それがイベントなのか、何年なのかってコンテンツ実体やそのテーマからしたら意味薄いしね。

@yamanoku どう？

**Comment by yamanoku** [comment]
遅レスすみません！

> なんならまとめを作った人の裁量で「2019年のアクセシビリティ関連イベントでスライドが公開されている一覧」とか「動画アーカイブがある一覧」とかそういう尺度になっていても良くて、それらのまとめをaccrefsでまとめているという構造になっている方が俯瞰しやすいなって思うのです。

たとえば2019年でもまとめページ自体は複数あってもいいってことですよね？（a11y_stepで使ってたDropboxとか、まったく知らない個人の方がまとめていたページとか）
んで個別で載せたい情報は、他のタグ付けでいつもどおりコンテンツ追加したらいい、みたいな。

自分の理解で相違なければいいと思います！

**Comment by oti** [comment]
ではアサインしてタグ切ります。

**Comment by oti** [comment]
進捗報告です。まだ何もやってません。

**Comment by magi1125** [comment]
otiさんがタグ作ってくれたのでclose
