### ISSUE TITLE
[Enhancement] 機能追加要望

### ISSUE THREAD

**Issue by oti** [a11yj/accrefs#83]
もう少し使いやすくするために、下記の機能の追加をリクエストします。

- ダークテーマの切り替え機能
- サイト内検索機能
- 小さくて愛らしいタグ一覧表示

誰か頼んだ！出なければ僕がやります。

**Comment by yamanoku** [comment]
> ダークテーマの切り替え機能

現状ダークテーマのCSS設定とかがないからもそれも必要そうですね
やってみますー

**Comment by oti** [comment]
#119 と #120 でほぼ対応できたので resolve とします〜
