### ISSUE TITLE
[Enhancement] ダークテーマ切り替え

### ISSUE THREAD

**Issue by yamanoku** [a11yj/accrefs#85]
Issue by #83

- CSS
- 切り替えボタン（ダークモード設定がないOS配慮）

**Comment by oti** [comment]
OS側の設定に合わせて自動で切り替わる設定はあんまり好きじゃないので、能動的にトグルするボタンなどがあればいいと思っていますが、自動で切り替わった方がいいと言う意見もあると思うので、ビジュアルも含めてどう実装するかを議論したいです。

**Comment by yamanoku** [comment]
トグルボタンでも出来て、OS側の設定でも出来る感じがいいかなと。
あとボタンはどこに設置するかですかね

実装参考になりそうなもの
https://github.com/hayatoito/hayatoito.github.io/blob/source/src/site.js

**Comment by oti** [comment]
#120 で対応できました。
