### ISSUE TITLE
[AddRequest] 2020年イベント・登壇資料まとめ

### ISSUE THREAD

**Issue by YusukeHirao** [a11yj/accrefs#90]
リストアップ自体は済んでますので、追加する資料を精査するところからだと思います。
https://docs.google.com/spreadsheets/d/1arkC7gyVZ11KmHWWSmrGejNkeHFCP6-G82ZaDetEEaE/edit#gid=0
（このスライドは編集可にしてますが、a11y_stepの勉強会の資料としても活用予定で2021年分も随時追記しています）

作業分担や実施はSlackの#accrefs_online_contributionに戻るかもしれませんが、Issueとして登録します。

**Comment by oti** [comment]
ありがとうございます！！！

**Comment by oti** [comment]
@YusukeHirao 長らく放置してしまって申し訳ありません。

せんだっての更新作業で @magi1125 と議論したのですが、イベント自体のリンクは取り扱わない方針となりました。なのでこのイシューは close させてください:bow:

しかし貼っていただいたスプシーの有用性はあると思うので、 例えば AY11J Slack で共有したり、[yamanoku 氏がやっているような形](https://github.com/yamanoku/awesome-japanese-a11y-companies)で世に出されるといいかもしれません。

**Comment by YusukeHirao** [comment]
@oti ありがとうございます！
時を経て、供養できてよかったです！
